project:
  type: website
  # render:
  #   - basics.qmd
  #   - Simple_GHAs/*.qmd
  #   - RAMP_example_dash.qmd

website:
  title: "GitHub Actions Workshop"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: basics.qmd
        text: Basics
      - section: "Simple GitHub Actions"
        href: Simple_GHAs/index.qmd
        contents:
        - href: Simple_GHAs/Anatomy_of_GHA_YAML.qmd
          text: Anatomy of a GitHub Actions YAML
        - href: Simple_GHAs/Adding_more_steps.qmd
          text: Adding more `steps`
        - href: Simple_GHAs/Config_events.qmd
          text: Configuring `events`
      - section: "Complex GitHub Actions"
        href: Complex_GHAs/index.qmd
        contents:
        - href: Complex_GHAs/Run_scripts.qmd
          text: Run scripts and use secrets
        - href: Complex_GHAs/Run_multiple_jobs.qmd
          text: Run multiple `jobs` in a workflow
        - href: Complex_GHAs/Workflow_artifacts.qmd
          text: Store and share data with artifacts
      - section: "Examples"
        contents:
        - href: example.qmd
          text: Standard report
        - href: RAMP_example_dash.qmd
          text: Dashboard
        - href: validate_example.qmd
          text: Data validation

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute: 
  warning: false
  message: false
  echo: false

