project:
  type: website

website:
  title: "GitHub Actions Workshop"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: "Examples"
        contents:
        - href: example.qmd
          text: Standard report
        - href: RAMP_example_dash.qmd
          text: Dashboard

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute: 
  warning: false
  message: false
  echo: false

