project:
  type: website

website:
  title: "GitHub Actions Workshop"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - example.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute: 
  warning: false
  message: false
  echo: false

