project:
  type: website

website:
  title: "GitHub Actions Workshop"
  repo-url: https://github.com/joshcullen/github_actions_workshop
  repo-actions: [issue, source]
  announcement: 
    icon: info-circle
    dismissable: true
    content: "Recording of the workshop is now available."
    type: success
    position: below-navbar
  sidebar:
    style: "docked"
    search: true
    tools:
      - icon: github
        href: https://github.com/joshcullen/github_actions_workshop
    contents:
      - href: index.qmd
        text: Home
      - href: basics.qmd
        text: Basics
      - section: "Simple GitHub Actions"
        href: Simple_GHAs/index.qmd
        contents:
        - href: Simple_GHAs/Anatomy_of_GHA_YAML.qmd
          text: Anatomy of a GitHub Actions YAML
        - href: Simple_GHAs/Adding_more_steps.qmd
          text: Adding more `steps`
        - href: Simple_GHAs/Config_events.qmd
          text: Configuring `events`
      - section: "Complex GitHub Actions"
        href: Complex_GHAs/index.qmd
        contents:
        - href: Complex_GHAs/Run_scripts.qmd
          text: Run scripts and use secrets
        - href: Complex_GHAs/Run_multiple_jobs.qmd
          text: Run multiple `jobs` in a workflow
        - href: Complex_GHAs/Workflow_artifacts.qmd
          text: Store and share data with artifacts
        - href: Complex_GHAs/R_pkg_check.qmd
          text: Check and test R packages
      - section: "Examples"
        contents:
        - href: std_report.qmd
          text: Standard report
        - href: RAMP_example_dash.qmd
          text: Dashboard
        - href: validate_example.qmd
          text: Data validation
        - href: https://joshcullen.github.io/CEG_operationalization/lbst_cmems
          text: Operationalized species distribution model
        - href: https://cciea-esr.github.io/CCIEA-uploader/
          text: CCIEA Uploader
  back-to-top-navigation: true
  page-footer:
    left: |
      &copy; 2025 Josh Cullen
    right: |
      This page is built with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)
  google-analytics: 
    tracking-id: "G-MVQW3P92B4"
  cookie-consent:
    type: implied
    style: simple
    palette: light

format:
  html:
    link-external-newwindow: true
    respect-user-color-scheme: true
    theme:
      light: [flatly, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    css: styles.css
    toc: true
    axe: true

execute: 
  warning: false
  message: false
  echo: false

