project:
  type: website
  render:
    - basics.qmd
    - Simple_GHAs/*.qmd

website:
  title: "GitHub Actions Workshop"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: basics.qmd
        text: Basics
      - section: "Simple GitHub Actions"
        contents:
        - href: Simple_GHAs/Anatomy_of_GHA_YAML.qmd
          text: Anatomy of a GitHub Actions YAML
        - href: Simple_GHAs/Adding_more_steps.qmd
          text: Adding more `steps`
      - section: "Complex GitHub Actions"
      - section: "Examples"
        contents:
        - href: example.qmd
          text: Standard report
        - href: RAMP_example_dash.qmd
          text: Dashboard
        - href: validate_example.qmd
          text: Data validation

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute: 
  warning: false
  message: false
  echo: false

