name: Share data with artifacts

on:
  schedule:
    - cron: '0 10 * * *'  #run daily at 6 am EDT (UTC-04:00)
  workflow_dispatch:

jobs:  
  dl_sst: 
    runs-on: ubuntu-latest
    steps:  
    - name: Check out repository  
      uses: actions/checkout@v5  

    - name: Install R
      uses: r-lib/actions/setup-r@v2  
    
    - name: Install R packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache: always
        packages: |
          any::glue
          any::terra
          any::ncdf4
      
    - name: Download and export SST
      shell: Rscript {0}
      run: source("Complex_GHAs/src/download_export_sst.R")
      
    - name: Upload SST artifact
      uses: actions/upload-artifact@v4
      with:
        name: erddap_sst
        path: mab_sst.nc
        retention-days: 1
 
 

  mean_sst: 
    runs-on: ubuntu-latest
    needs: dl_sst
    steps:  
    - name: Check out repository  
      uses: actions/checkout@v5  
    
    - name: Download artifact w SST data
      uses: actions/download-artifact@v5
      with:
        name: erddap_sst
        path: .

    - name: Install geospatial dependencies (e.g., GDAL)
      run: |
        sudo apt-get update
        sudo apt-get install -y libgdal-dev gdal-bin
    
    - name: Install xarray and other deps from existing reqs file
      run:  pip install -r requirements.txt
    
    - name: Calculate mean SST
      run: python Complex_GHAs/src/summarize_sst.py
