name: Run Python script
on:
  workflow_dispatch:

jobs:  
  run_python: 
    runs-on: ubuntu-latest
    steps:  
    - name: Check out repository  
      uses: actions/checkout@v5  

    - name: Install Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        channels: conda-forge,defaults
        python-version: 3.12
    
    - name: Install Python packages
      run: pip install -r requirements.txt
    
    - name: Download and summarize SST
      run: |
        python Complex_GHAs/src/download_export_sst.py
        python Complex_GHAs/src/summarize_sst.py