name: Install GDAL and CDO

on: workflow_dispatch

jobs:  
  install_gdal_cdo: 
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash  # <1>
    steps:  
    - name: Check out repository  
      uses: actions/checkout@v5  

    - name: Install geospatial libraries
      run: |
        sudo apt-get update
        sudo apt-get install libudunits2-dev gdal-bin libgdal-dev libgeos-dev libproj-dev libsqlite3-dev  # <2>
    
    - name: Install CDO
      run: sudo apt-get install cdo  # <3>
      
    - name: Check software versions
      run: |
        gdalinfo --version  #check GDAL version
        cdo -V  #check CDO version