
name: MATLAB example

on:
  # triggered on push to repo
  # push:
  #   branches: main
  # triggered by cron job
  schedule:
    # * is a special character in YAML so you have to quote this string
    # https://crontab.cronhub.io
    - cron:  '30 10 * * *'  #scheduled to run at 10:30 am UTC every day
  # triggered by manual activation on GitHub repo website
  workflow_dispatch:

jobs:
  matlab_test:
    runs-on: windows-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      
    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v2
      with:
        release: R2024a
        
    - name: Run script
      uses: matlab-actions/run-command@v2
      with:
        command: addpath("MATLAB_example"), matlab_example_SoCalSST

    - name: Commit and Push Changes
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

        git add .
        git commit -m 'Updated CSV file'
        git push


  update-website:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    
    - name: Install R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4.3'

    - name: Install R packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 4
        extra-packages: |
          any::tidyverse
          any::DT

    - name: Render and Publish
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: gh-pages
        # path: website
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}